"""Added Blog model

Revision ID: 0fa14075b058
Revises: c67848fa3dea
Create Date: 2025-05-05 09:36:17.391811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa14075b058'
down_revision = 'c67848fa3dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        
        # Drop the foreign key constraint by name
        batch_op.drop_constraint('fk_blogs_user_id', type_='foreignkey')  # Replace with actual constraint name
        
        # Create new foreign key
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])
        
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        # Drop the foreign key constraint by name (ensure the correct constraint name is used here)
        batch_op.drop_constraint('blogs_user_id_fkey', type_='foreignkey')
  # Replace with actual constraint name
        
        # Re-create the foreign key constraint if needed
        batch_op.create_foreign_key('blogs_user_id_fkey', 'users', ['user_id'], ['id'])
        
        batch_op.drop_column('created_at')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
