"""Initial migration

Revision ID: 281a0322eea9
Revises: a2675c211150
Create Date: 2025-05-10 00:53:08.807539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281a0322eea9'
down_revision = 'a2675c211150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('size')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
