"""Added created_at field to Blog model

Revision ID: 71b4c52ba1f4
Revises: 597675e6a1e7
Create Date: 2025-05-06 20:34:44.140759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b4c52ba1f4'
down_revision = '597675e6a1e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
